# Generated by Django 3.0.8 on 2020-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
